version: '3'
services:
  code-sandbox:
    container_name: sandbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8198:8198"
    networks:
      - mynetwork

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
